AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for cross account deploy

Parameters:
  ProjectName:
    Type: String
    Default: hs-cross-01
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [ !Ref ProjectName, "app", "ec2", "role" ] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/EC2InstanceConnect"
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role
  EC2:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: [ ]
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
                files:
                  - "/etc/httpd/httpd.conf"
                sources:
                  - "/var/www/html"
          files:
            /var/www/html/index.html:
              content: !Sub |
                It works! ${AWS::StackName}!!
              mode: "000600"
              owner: "apache"
              group: "apache"
    Properties:
      ImageId: "ami-0bba69335379e17f8"
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref SecurityGroupId
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: aws-rirazou0101
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref ProjectName, "app", "ec2" ] ]
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region}
